version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news_db
    ports:
      - "3307:3306"  # تغییر پورت محلی به 3307
    volumes:
      - db_data:/var/lib/mysql

  flask_app:
    build: .
    container_name: flask_app_container
    depends_on:
      - db
    ports:
      - "5001:5000"  # تغییر پورت محلی به 5001
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=news_db

volumes:
  db_data:
